# Generated by Django 4.2.11 on 2024-05-07 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channeltsrecord',
            old_name='ts',
            new_name='ts_jp',
        ),
        migrations.RemoveField(
            model_name='channeltsrecord',
            name='cid',
        ),
        migrations.AddField(
            model_name='channeltsrecord',
            name='cid_jp',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='channeltsrecord',
            name='cid_vn',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='channeltsrecord',
            name='name_jp',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='channeltsrecord',
            name='name_vn',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='channeltsrecord',
            name='ts_vn',
            field=models.CharField(default='', max_length=20),
        ),
    ]
