# Generated by Django 4.2.11 on 2024-05-07 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_ts_channeltsrecord_ts_jp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channeltsrecord',
            name='name_jp',
        ),
        migrations.RemoveField(
            model_name='channeltsrecord',
            name='name_vn',
        ),
    ]
