# Generated by Django 4.2.11 on 2024-05-10 07:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_systemmessagerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='logrecord',
            name='data',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='taskrecord',
            name='data',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='logrecord',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
