# Generated by Django 4.2.11 on 2024-05-11 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_logrecord_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logrecord',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
