# Generated by Django 4.2.11 on 2024-05-14 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_logrecord_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingEventRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
